// nodes/textNode.js
// ═══════════════════════════════════════════════════════════════════════
// The Text node is special — it has:
// 1. An inline auto-resizing textarea directly on the node
// 2. Dynamic {{variable}} handle creation as user types
// This is why it's NOT generated by createNode() and is hand-crafted.
// ═══════════════════════════════════════════════════════════════════════

import { BaseNode } from './BaseNode';
import { FileText } from 'lucide-react';
import { Handle, Position } from 'reactflow';
import { useMemo, useRef, useEffect, useCallback } from 'react';
import { useStore } from '../store';
import { motion, AnimatePresence } from 'framer-motion';

// Parse {{variableName}} — only valid JS identifiers
const extractVars = (text) => {
  const regex = /\{\{\s*([a-zA-Z_$][a-zA-Z0-9_$]*)\s*\}\}/g;
  const vars = [];
  let match;
  while ((match = regex.exec(text)) !== null) {
    if (!vars.includes(match[1])) vars.push(match[1]);
  }
  return vars;
};

export const TextNode = ({ id, data, selected }) => {
  const text = data?.text ?? '{{input}}';
  const vars = useMemo(() => extractVars(text), [text]);
  const updateNodeField = useStore((s) => s.updateNodeField);
  const textareaRef = useRef(null);
  const mirrorRef = useRef(null);

  const accentColor = 'var(--accent-amber)';

  // Auto-resize: measure a hidden mirror div to get true content dimensions
  useEffect(() => {
    const ta = textareaRef.current;
    const mirror = mirrorRef.current;
    if (!ta || !mirror) return;

    // Copy textarea content to mirror for measuring
    mirror.textContent = text + '\n';

    // Height: match content height (min 36px, max 200px)
    const scrollH = Math.max(36, Math.min(mirror.scrollHeight, 200));
    ta.style.height = scrollH + 'px';

    // Width: grow node based on longest line (min 200px, max 400px)
    const lines = text.split('\n');
    const longestLine = lines.reduce((a, b) => (a.length > b.length ? a : b), '');
    // Rough char-width estimate at 7.2px per char in monospace 12px
    const estimatedWidth = Math.max(200, Math.min(longestLine.length * 7.2 + 40, 400));
    const node = ta.closest('.base-node');
    if (node) {
      node.style.minWidth = estimatedWidth + 'px';
    }
  }, [text]);

  const handleChange = useCallback(
    (e) => {
      updateNodeField(id, 'text', e.target.value);
    },
    [id, updateNodeField]
  );

  // Handle positions for dynamic variable handles
  const getVarHandleTop = (index, total) => {
    if (total === 1) return '50%';
    const start = 25;
    const end = 75;
    return `${start + (index / (total - 1)) * (end - start)}%`;
  };

  return (
    <BaseNode
      id={id}
      title="Text"
      icon={FileText}
      accentColor={accentColor}
      outputs={[{ id: 'output', label: 'output' }]}
      selected={selected}
      data={data}
      minWidth={220}
    >
      {/* Hidden mirror for auto-size measurement */}
      <div
        ref={mirrorRef}
        aria-hidden="true"
        style={{
          position: 'absolute',
          visibility: 'hidden',
          whiteSpace: 'pre-wrap',
          wordWrap: 'break-word',
          fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
          fontSize: '12px',
          lineHeight: '1.5',
          padding: '10px 12px',
          width: '100%',
          boxSizing: 'border-box',
          pointerEvents: 'none',
        }}
      />

      {/* Inline auto-resizing textarea */}
      <textarea
        ref={textareaRef}
        className="text-node-textarea"
        value={text}
        onChange={handleChange}
        placeholder="Enter text... Use {{variable}} for dynamic inputs"
        spellCheck={false}
      />

      {/* Variable chips */}
      <AnimatePresence>
        {vars.length > 0 && (
          <motion.div
            className="text-node-vars"
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
          >
            {vars.map((v) => (
              <motion.span
                key={v}
                className="text-node-var-chip"
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.8 }}
                transition={{ duration: 0.2 }}
              >
                {v}
              </motion.span>
            ))}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Dynamic variable handles on the left side */}
      <AnimatePresence>
        {vars.map((v, i) => (
          <motion.div
            key={v}
            initial={{ opacity: 0, x: -8 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -8 }}
            transition={{ duration: 0.2, delay: i * 0.05 }}
            style={{
              position: 'absolute',
              left: 0,
              top: getVarHandleTop(i, vars.length),
              transform: 'translateY(-50%)',
            }}
          >
            <Handle
              type="target"
              position={Position.Left}
              id={`var-${v}`}
              className="base-node-handle"
              style={{ '--handle-color': accentColor }}
            />
            <span className="text-node-var-label">{v}</span>
          </motion.div>
        ))}
      </AnimatePresence>
    </BaseNode>
  );
};
